# Generated by Django 3.2.6 on 2022-07-23 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500, null=True)),
                ('xp', models.IntegerField(default=0, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('interest', models.CharField(default='startic-field,', max_length=200, null=True)),
                ('social', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('public', models.BooleanField(default=True)),
                ('desc', models.TextField(max_length=1000)),
                ('tags', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='programs/')),
                ('live_date', models.DateField()),
                ('team_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('members', models.CharField(max_length=500, null=True)),
                ('social1', models.CharField(max_length=200, null=True)),
                ('social2', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('supporters', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.profile')),
            ],
        ),
    ]
