# Generated by Django 3.2.6 on 2022-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventmap',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
