# Generated by Django 3.2.6 on 2022-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_event_usereventmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='live_date',
            field=models.DateTimeField(),
        ),
    ]
