# Generated by Django 3.2.6 on 2022-07-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220725_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgramForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('answer1', models.TextField(max_length=1200, null=True)),
                ('answer2', models.TextField(max_length=2000, null=True)),
                ('answer3', models.TextField(max_length=3000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='team_needed',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team'), ('Mix', 'Mix')], default='Team', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='question1',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='question2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='question3',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='UserProgramMap',
        ),
        migrations.AddField(
            model_name='userprogramform',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.program'),
        ),
        migrations.AddField(
            model_name='userprogramform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.profile'),
        ),
    ]
