# Generated by Django 3.2.6 on 2022-07-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220725_0111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProgramForm',
            new_name='UserProgram',
        ),
    ]
