# Generated by Django 3.2.6 on 2022-07-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_reversepitch_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversepitch',
            name='desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reversepitch',
            name='tags',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reversepitch',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
