# Generated by Django 3.2.6 on 2022-07-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_userprogram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
