# Generated by Django 3.2.6 on 2022-07-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20220725_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendartoken',
            old_name='expires_in',
            new_name='expiry',
        ),
        migrations.RemoveField(
            model_name='calendartoken',
            name='token_type',
        ),
    ]
